// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ndnalmzmzpfyygvwwurq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5kbmFsbXptenBmeXlndnd3dXJxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3MTI1MDQsImV4cCI6MjA2MzI4ODUwNH0.svDif0CSgQ2x-43lpNCX1qeb-r7ejsJSrD24lfdEr4k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);